apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s1ie-exams
spec:
  rules:
    - host: s1ie.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s1ie-exams
                port:
                  number: 80
