apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Override image for minikube to use the locally-built image
images:
  - name: srinugalla/s1ie-exams
    newName: s1ie-exams
    newTag: local

patchesStrategicMerge:
  - patch-imagepull.yaml
